server:
  port : 8081
  servlet:
    context-path: /psicalendar/api/
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:psicalendardb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop